<?php

/**
 * @file
 * Contains people.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function people_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the people module.
    case 'help.page.people':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('IDM People/Team functions') . '</p>';
      $output .= '<p>' . t('... first goal is to create a dynamic profile page');
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 * Declare a new theme
 */
function people_theme() {

  // No idea if this really does anything
  return [
    'people_profile' => [
      'variables' => [
        'content' => '',
      ],
    ],
    'people_profile_mobile' => [
      'variables' => [
        'content' => '',
        'attributes' => array(),
      ],
    ],
  ];
}



/**
 * @param $variables
 */
function people_preprocess_container(&$variables) {

  $variables['no_swap'] = TRUE;

  // This needs to be very specific to the view in question
  if (isset($variables['attributes']['class'])) {

    if ($variables['attributes']['class'][0] == 'views-element-container') {

      if ($variables["element"]["#name"] == 'publications_listings') {
        // Adding the preprocess var "profile_swap" is redundant;
        $variables['attributes']['class'][0] = 'auto-col';
        $variables['attributes']['class'][] = 'profile-swap';
        //@todo This item (I think) is showing up in the list of classes as "1"
        $variables['no_swap'] = FALSE;
      }
    }
  }

}