
<?php

/**
 * @file
 * Contains migrate_publications.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_publications_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_publications module.
    case 'help.page.migrate_publications':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom migration for Publications nodes') . '</p>';
      return $output;

    default:
  }
}
