<?php

/**
 * @file
 * Contains idmblocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function idmblocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the idmblocks module.
    case 'help.page.idmblocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom IDM Blocks') . '</p>';
      return $output;

    default:
  }
}
